apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: 2018-05-09T15:01:04Z
  generation: 1
  labels:
    run: nginx-example
  name: nginx-example
  namespace: default
  resourceVersion: "5745"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nginx-example
  uid: cbbbbbb7-5399-11e8-ada9-c2119cfeef39
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: nginx-example
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx-example
    spec:
      containers:
      - image: nginx:1.13.5-alpine
        imagePullPolicy: IfNotPresent
        name: nginx-example
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
