apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-05-09T15:03:51Z
  labels:
    run: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: nginx-example
  namespace: default
  resourceVersion: "5963"
  selfLink: /api/v1/namespaces/default/services/nginx-example
  uid: 2f4b498e-539a-11e8-ada9-c2119cfeef39
spec:
  clusterIP: 10.106.154.226
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31208
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: "{{ .Release.Name }}"
  sessionAffinity: None
  type: "{{ .Values.service.type }}"
status:
  loadBalancer: {}
